// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesModuleScssNamespace {
  export interface IStylesModuleScss {
    antialiased: string
    bottom0: string
    fixed: string
    flex: string
    fontBold: string
    hScreen: string
    header: string
    headerTitle: string
    itemsCenter: string
    justifyCenter: string
    left0: string
    m0: string
    pb2: string
    right0: string
    textCenter: string
    textXs: string
    top0: string
    underline: string
    uppercase: string
  }
}

declare const StylesModuleScssModule: StylesModuleScssNamespace.IStylesModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesModuleScssNamespace.IStylesModuleScss
}

export = StylesModuleScssModule
